export const LOGIN = 'LOGIN'
export const LOGIN_OUT = 'LOGIN_OUT'
export const UPDATE_USER = 'UPDATE_USER'
export const GET_USER = 'GET_USER'
export const CLEAR_USER = 'CLEAR_USER'
export const CHANGE_LOGIN = 'CHANGE_LOGIN'
export const REST_USER = 'REST_USER'
// export const RECEIVE_PRODUCTS = 'RECEIVE_PRODUCTS'
